Adding in a tmux deploy and moving backups into a bash func

diff --git a/deploy-dotfiles b/deploy-dotfiles
--- a/deploy-dotfiles
+++ b/deploy-dotfiles
@@ -14,6 +14,24 @@ if [[ -z ${CWD} ]]; then
     exit 1
 fi
 
+# functions
+check_link_and_backup () {
+    backupdir=$1
+    file=$2
+
+    # check that backupdir exists
+    if [[ ! -d ${backupdir} ]]; then
+        echo "Error, the backup directory '${backupdir}', does not exist"
+        exit 1
+    fi
+    # check to see if the file is a link, if not, backup
+    if [[ ! -L $1 ]]; then
+        mkdir -pv ${backupdir}/$(basename ${file}).${reponame}-${tstamp}
+        mv --verbose ${file} ${backupdir}/$(basename ${file}).${reponame}-${tstamp}
+    fi
+}
+
+
 ############################# SCAFFOLDING ######################################
 # test for the git command
 git=$(which git)
@@ -54,10 +72,11 @@ fi
 for dir in $(find ${CWD}/${CONFDIR} -mindepth 1 -maxdepth 1 -type d); do
     dir=$(basename ${dir})
     echo ${dir}
-    echo mv --verbose ${HOME}/.${CONFDIR}/${dir} ${BACKUP}/${CONFDIR}.${reponame}-${tstamp}/${dir}
-    echo ln --symbolic --verbose ${CWD}/${CONFDIR}/${dir} ${HOME}/.${CONFDIR}/
+    if [[ ! -L ${HOME}/.${CONFDIR}/${dir} ]]; then
+        echo mv --verbose ${HOME}/.${CONFDIR}/${dir} ${BACKUP}/${CONFDIR}.${reponame}-${tstamp}/${dir}
+        echo ln --symbolic --verbose ${CWD}/${CONFDIR}/${dir} ${HOME}/.${CONFDIR}/
+    fi
 done
-exit 0
 
 ################################# BASH #########################################
 echo "Copying bash dotfiles to ${HOME}"
@@ -146,5 +165,13 @@ if [[ -d ${OPT}/powerline/powerline/bindings/vim && -d ${HOME}/.vim/bundle ]]; t
 fi
 
 ################################# TMUX #########################################
+file='tmux.conf'
+echo "Linking file '${file}' to '${HOME}'"
+if [[ -f ${HOME}/.${file} ]]; then
+    mv -v ${HOME}/.${file} ${BACKUP}/.${file}.${reponame}-${tstamp}
+    ln --symbolic --verbose ${CWD}/${file} ${HOME}/.${file}
+elif [[ -L ${HOME}/.${file} ]]; then
+    cp -v ${HOME}/.${file} ${BACKUP}/.${file}.${reponame}-${tstamp}
+fi
 
 
